import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { GetStaticPropsContext } from "next";
import Link from "next/link";

interface SsgProps {
  elements: [any];
}

const IsgPage: NextPage<SsgProps> = ({ elements }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ISR{" "}
          <Link href="/">
            <a>Voltar</a>
          </Link>
        </h1>

        {elements.map((element: any) => (
          <p key={element.id} className={styles.description}>
            <span>
              {element.title} - {element.date}
            </span>
          </p>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getStaticProps(context: GetStaticPropsContext) {
  const elements = [
    {
      id: 1,
      title: "getStaticProps with revalidate",
      date: new Date().toISOString(),
    },
  ];
  return {
    props: { elements }, // will be passed to the page component as props
    revalidate: 10, // seconds
  };
}

export default IsgPage;
