/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import Link from "next/link";

interface ElementProps {
  id: number;
  title: string;
  date: string;
}

const ReactPage: NextPage = () => {
  const [elements, setElements] = useState<ElementProps[]>([]);

  useEffect(() => {
    setElements([
      {
        id: 1,
        title: "React useEffect / useState",
        date: new Date().toISOString(),
      },
    ]);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          React useEffect / useState{" "}
          <Link href="/">
            <a>Voltar</a>
          </Link>
        </h1>

        {elements.map((element: any) => (
          <p key={element.id} className={styles.description}>
            <span>
              {element.title} - {element.date}
            </span>
          </p>
        ))}

        {/* <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br /> */}
        <div style={{display: "flex", flexDirection: "row"}}>
          <div style={{ backgroundColor: "blue" }}>
            <img src="https://pentagrama.com.br/img/logo.png" />
            <br />
            <img src="https://designculture.com.br/wp-content/uploads/2017/06/muié.png" width="300" />
          </div>

          <div style={{ backgroundColor: "blue" }}>
            <Image
              src="https://pentagrama.com.br/img/logo.png"
              width={257}
              height={55}
            />
            <br />
            <Image
              src="https://designculture.com.br/wp-content/uploads/2017/06/mui%C3%A9.png"
              width={300}
              height={184}
            />
          </div>

          <div style={{ backgroundColor: "blue" }}>
            <Image
              src="https://pentagrama.com.br/img/logo.png"
              width={257}
              height={55}
              priority={true}
            />
            <br />
            <Image
              src="https://designculture.com.br/wp-content/uploads/2017/06/mui%C3%A9.png"
              width={300}
              height={184}
              priority={true}
            />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default ReactPage;
